"""
تعريف حالات المحادثة (Conversation States)
التسلسل الجديد: تخصص ← خدمة ← كتلة ← مواد (مع سلة مشتريات)
"""

# --- حالات محادثة الطالب ---
(WELCOME, CHOOSE_SPEC, CHOOSE_SERVICE, CHOOSE_BLOCK, CHOOSE_COURSES,
 CHOOSE_PAYMENT, GET_PAYMENT_INFO, CONFIRM_ORDER, SEARCH_COURSES,
 VIEW_CART) = range(10)

# --- حالات محادثة إدارة المحتوى (أدمن) ---
(ADMIN_MENU, CONTENT_AREA, SELECT_SPEC, SELECT_SERVICE_ADMIN, SELECT_ACTION,
 AWAIT_INPUT, AWAIT_CONFIRMATION, ADMIN_BLOCK_SELECT,
 BLOCK_MANAGE_COURSES, AWAIT_NEW_COURSE_NAME,
 MANAGE_COURSES_PAGE, AWAIT_DELETE_COURSE_CONFIRM) = range(10, 22)

# --- حالات محادثة إدارة طرق الدفع ---
(PAYMENT_MENU, SELECT_PAYMENT_ACTION, AWAIT_PAYMENT_NAME,
 AWAIT_PAYMENT_DETAILS, AWAIT_EDIT_PAYMENT_DETAILS,
 AWAIT_PAYMENT_CONFIRMATION, AWAIT_DELETE_CONFIRMATION,
 AWAIT_PAYMENT_IMAGE) = range(22, 30)

# --- حالات البث ---
(ADMIN_BROADCAST, BROADCAST_PREVIEW, BROADCAST_SCHEDULE) = range(30, 33)
